# Manhattan Similarity [맨하탄 유사도] 구하기

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
docs = [
    '나는 오늘 기분이 좋아',
    '나는 항상 기분이 좋아',
    '우리는 매일 기분이 나빠',
    '너는 항상 나빠 나빠'
]

In [8]:
docs2 = ( "휴일 인 오늘 도 서쪽 을 중심 으로 폭염 이 이어졌는데요, 내일 은 반가운 비 소식 이 있습니다.", 
            "폭염 을 피해서 휴일 에 놀러왔다가 갑작스런 비 로 인해 망연자실 하고 있습니다.")

In [9]:
# TF-IDF 객체선언
tfidfv = TfidfVectorizer()
# tf-idf 계산
tfidf_matrix = tfidfv.fit_transform(docs2)
tfidf_matrix

<2x17 sparse matrix of type '<class 'numpy.float64'>'
	with 20 stored elements in Compressed Sparse Row format>

## Manhattan Distance구하기

In [10]:
import numpy as np

# 0 ~ 1 사이값을 가지도록 정규화 시킴
def l1_normalize(v):
    norm = np.sum(v)
    return v / norm 
  
# L1 정규화  
tfidf_norm_l1 = l1_normalize(tfidf_matrix)

# sklearn - 맨하탄 유사도
from sklearn.metrics.pairwise import manhattan_distances

In [11]:
tfidf_norm_l1[0:1]

<1x17 sparse matrix of type '<class 'numpy.float64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [12]:
manhattan_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])

array([[0.77865927]])

In [6]:
manhattan_distances(tfidf_norm_l1[1:2], tfidf_norm_l1[2:3])

array([[0.42492107]])

In [7]:
manhattan_distances(tfidf_norm_l1[2:3], tfidf_norm_l1[3:4])

array([[0.35848302]])